name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: npm install, build, and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Cache node modules
        id: cacheNpmModules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cacheNpmModules.outputs.cache-hit != 'true'
        run: npm install

      - run: npm run build
